# core-utilities.yml
- name: "Bootstrap a new Linux environment (Debian/Fedora/Arch)"
  hosts: localhost
  connection: local

  vars:
    # --- Automatically discover the user who ran the playbook ---
    bootstrap_user: "{{ ansible_user_id }}"

    # --- Packages with identical names across all distros ---
    common_packages:
      - git
      - curl
      - fish
      - lsd
      - bat
      - fzf
      - zoxide
      - duf
      - mc
      - entr
      - tealdeer
      - btop
      - micro
      - thefuck
      - figlet
      - cowsay
      - fortune-mod

    # --- Distro-Specific Packages (Official Repositories Only) ---
    debian_packages:
      - 7zip
      - fonts-firacode
      - fortune-anarchism
      - anarchism
    fedora_packages:
      - cascadia-code-nf-fonts
      - chezmoi
    arch_official_packages:
      - 7zip
      - ttf-firacode-nerd
      - chezmoi
      - base-devel # Required to build AUR packages

    # --- AUR-Only Packages (for Arch Linux) ---
    arch_aur_packages:
      - fortune-mod-anarchism
      - anarchism

  tasks:
    # --- Official Package Installation (Requires privilege escalation) ---
    - name: "Update package cache and install packages (Debian)"
      become: yes
      ansible.builtin.apt:
        name: "{{ common_packages + debian_packages }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install packages (Fedora)"
      become: yes
      ansible.builtin.dnf:
        name: "{{ common_packages + fedora_packages }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: "Install Official Packages (Arch)"
      become: yes
      community.general.pacman:
        name: "{{ common_packages + arch_official_packages }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Archlinux"

    # --- AUR Package Installation (Arch Linux Only) ---
    - name: "Build and install yay AUR helper"
      when: ansible_os_family == "Archlinux"
      block:
        - name: "Clone yay repository"
          # This runs as the normal user
          ansible.builtin.git:
            repo: https://aur.archlinux.org/yay.git
            dest: "/home/{{ bootstrap_user }}/yay"
            force: yes

        - name: "Build yay package"
          # This runs as the normal user
          ansible.builtin.shell: "cd /home/{{ bootstrap_user }}/yay && makepkg -s --noconfirm"
          args:
            # Find the generated package file to know if build is needed
            creates: "/home/{{ bootstrap_user }}/yay/yay-*.pkg.tar.zst"

        - name: "Install yay package"
          become: yes # This runs as root
          ansible.builtin.shell: "pacman -U --noconfirm /home/{{ bootstrap_user }}/yay/yay-*.pkg.tar.zst"
          args:
            creates: /usr/bin/yay

    - name: "Install other AUR packages with yay"
      # This entire task now runs as the normal user.
      # `yay` will invoke `sudo` internally, and Ansible will supply the password
      # provided with --ask-become-pass.
      become: yes
      community.general.pacman:
        name: "{{ arch_aur_packages }}"
        state: present
        executable: yay

      when: ansible_os_family == "Archlinux"

    # --- System-Wide Configuration ---
    - name: "Link batcat to bat (Debian only)"
      become: yes
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /usr/local/bin/bat
        state: link
      when: ansible_os_family == "Debian"

    - name: "Install Chezmoi via script (Debian only)"
      become: yes
      ansible.builtin.shell: 'sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin'
      args:
        creates: /usr/local/bin/chezmoi
      when: ansible_os_family == "Debian"
