# core-utilities.yml
- name: "Bootstrap Ansible and System Dependencies"
  hosts: localhost
  connection: local

  vars:
    bootstrap_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    common_packages:
      - git
      - curl
      - fish
      - lsd
      - bat
      - fzf
      - zoxide
      - duf
      - mc
      - entr
      - tealdeer
      - btop
      - micro
      - thefuck
      - figlet
      - cowsay
      - fortune-mod
    debian_packages:
      - 7zip
      - fonts-firacode
      - fortune-anarchism
      - anarchism
    fedora_packages:
      - cascadia-code-nf-fonts
      - chezmoi
    arch_official_packages:
      - 7zip
      - ttf-firacode-nerd
      - chezmoi
    arch_aur_packages:
      - yay
      - fortune-mod-anarchism
      - anarchism

  tasks:
    # --- Stage 1: Bootstrap Ansible Itself ---
    - name: "Install required Ansible collections (if needed)"
      become: yes
      ansible.builtin.command: "ansible-galaxy collection install community.general community.aur"
      args:
        creates: "/root/.ansible/collections/ansible_collections/community/aur"
      changed_when: false

    - name: "Force Ansible to re-read collection paths"
      ansible.builtin.meta: flush_handlers

    # --- Stage 2: System Package Installation ---
    - name: "Update package cache and install packages (Debian)"
      become: yes
      ansible.builtin.apt:
        name: "{{ common_packages + debian_packages }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install packages (Fedora)"
      become: yes
      ansible.builtin.dnf:
        name: "{{ common_packages + fedora_packages }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: "Install Official Packages (Arch)"
      become: yes
      community.general.pacman:
        name: "{{ common_packages + arch_official_packages }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Archlinux"

    - name: "Install AUR Packages (Arch only)"
      become: yes
      become_user: "{{ bootstrap_user }}"
      community.aur.aur:
        name: "{{ arch_aur_packages }}"
        state: present
      when: ansible_os_family == "Archlinux"

    # --- Stage 3: System-Wide Configuration ---
    - name: "Link batcat to bat (Debian only)"
      become: yes
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /usr/local/bin/bat
        state: link
      when: ansible_os_family == "Debian"

    - name: "Install Chezmoi via script (Debian only)"
      become: yes
      ansible.builtin.shell: 'sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin'
      args:
        creates: /usr/local/bin/chezmoi
      when: ansible_os_family == "Debian"
