# playbook_package-managers.yml
# Installs packages using various package managers.
- name: "Initialize package variables and results tracker"
  set_fact:
    os_packages_common: "{{ os_packages_common | default([]) }}"
    os_packages_debian: "{{ os_packages_debian | default([]) }}"
    os_packages_fedora: "{{ os_packages_fedora | default([]) }}"
    os_packages_arch: "{{ os_packages_arch | default([]) }}"
    aur_packages: "{{ aur_packages | default([]) }}"
    pip_packages: "{{ pip_packages | default([]) }}"
    npm_packages: "{{ npm_packages | default([]) }}"
    cargo_packages: "{{ cargo_packages | default([]) }}"
    flatpak_packages: "{{ flatpak_packages | default([]) }}"
    brew_packages: "{{ brew_packages | default([]) }}"
    failed_installations: []

# --- Package Manager Setup (HARD FAILURES) ---
- name: "Ensure package managers are available"
  block:
    - name: "Check pip availability"
      when: pip_packages | length > 0
      command: which pip3 || which pip
      register: pip_check
      changed_when: false
      failed_when: pip_check.rc != 0

    - name: "Check npm availability"
      when: npm_packages | length > 0
      command: which npm
      register: npm_check
      changed_when: false
      failed_when: npm_check.rc != 0

    - name: "Check cargo availability or install it"
      when: cargo_packages | length > 0
      block:
        - name: "Check if cargo is available"
          command: which cargo
          register: cargo_check
          changed_when: false
          ignore_errors: yes

        - name: "Install cargo if missing"
          when: cargo_check.rc != 0
          become: yes
          shell: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          args:
            creates: "{{ ansible_env.HOME }}/.cargo/bin/cargo"

    - name: "Setup Flatpak for Flathub"
      when: flatpak_packages | length > 0
      block:
        - name: "Ensure Flatpak is installed"
          become: yes
          package:
            name: flatpak
            state: present
        - name: "Add Flathub repository"
          become: yes
          command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          args:
            creates: "/var/lib/flatpak/repo/flathub.flatpakrepo"

    - name: "Check Homebrew availability or install it"
      when: brew_packages | length > 0
      block:
        - name: "Check if Homebrew is available"
          command: which brew
          register: brew_check
          changed_when: false
          ignore_errors: yes
        - name: "Install Homebrew if missing"
          when: brew_check.rc != 0
          shell: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          args:
            creates: "/home/linuxbrew/.linuxbrew/bin/brew"
          environment:
            NONINTERACTIVE: 1

# --- Package Installation (CONTINUE ON INDIVIDUAL FAILURES) ---
- name: "Install all packages"
  block:
    # --- OS Packages ---
    # For Debian:
    - name: "Install Debian OS packages (common + specific)"
      when: ansible_os_family == "Debian" and (os_packages_common | length > 0 or os_packages_debian | length > 0)
      become: yes
      package:
        name: "{{ item.package_name }}"
        state: present
      loop: "{{ os_packages_common + os_packages_debian }}"
      loop_control:
        label: "Installing OS package: {{ item.name }} - {{ item.package_name }}"

    # For Fedora:
    - name: "Install Fedora OS packages (common + specific)"
      when: ansible_os_family == "RedHat" and (os_packages_common | length > 0 or os_packages_fedora | length > 0)
      become: yes
      package:
        name: "{{ item.package_name }}"
        state: present
      loop: "{{ os_packages_common + os_packages_fedora }}"
      loop_control:
        label: "Installing OS package: {{ item.name }} - {{ item.package_name }}"

    # For Arch:
    - name: "Install Arch OS packages (common + specific)"
      when: ansible_os_family == "Archlinux" and (os_packages_common | length > 0 or os_packages_arch | length > 0)
      become: yes
      community.general.pacman:
        name: "{{ item.package_name }}"
        state: present
        extra_args: "--noconfirm"
      loop: "{{ os_packages_common + os_packages_arch }}"
      loop_control:
        label: "Installing OS package: {{ item.name }} - {{ item.package_name }}"

    # - name: "Install Arch OS packages (common + specific)"
    #   when: ansible_os_family == "Archlinux" and (os_packages_common | length > 0 or os_packages_arch | length > 0)
    #   become: yes
    #   community.general.pacman:
    #     name: "{{ item.package_name }}"
    #     state: present
    #     extra_args: "--noconfirm --needed"
    #   loop: "{{ os_packages_common + os_packages_arch }}"
    #   loop_control:
    #     label: "Installing OS package: {{ item.name }} - {{ item.package_name }}"
    # For Arch:
    # - name: "Install Arch OS packages (common + specific)"
    #   when: ansible_os_family == "Archlinux" and (os_packages_common | length > 0 or os_packages_arch | length > 0)
    #   become: yes
    #   shell: |
    #     pacman --noconfirm --needed -S "{{ item.package_name }}"
    #   loop: "{{ os_packages_common + os_packages_arch }}"
    #   loop_control:
    #     label: "Installing OS package: {{ item.name }} - {{ item.package_name }}"
    #   args:
    #     executable: /bin/bash

    # --- Other Packages ---
    # AUR Packages
    - name: "Install AUR packages"
      when: ansible_os_family == "Archlinux" and aur_packages | length > 0
      become: yes
      become_user: aur_builder
      kewlfft.aur.aur:
        name: "{{ item.package_name }}"
        state: present
      loop: "{{ aur_packages }}"
      loop_control:
        label: "Installing AUR package: {{ item.name }} - {{ item.package_name }}"
      environment:
        HOME: "/home/aur_builder"

    # PIP Packages
    - name: "Install pip packages"
      when: pip_packages | length > 0 and pip_check.rc == 0
      become: yes
      pip:
        name: "{{ item.package_name }}"
        state: present
      loop: "{{ pip_packages }}"
      loop_control:
        label: "Installing PIP package: {{ item.name }} - {{ item.package_name }}"

    # NPM Packages
    - name: "Install npm packages"
      when: npm_packages | length > 0 and npm_check.rc == 0
      become: yes
      npm:
        name: "{{ item.package_name }}"
        state: present
        global: yes
      loop: "{{ npm_packages }}"
      loop_control:
        label: "Installing NPM package: {{ item.name }} - {{ item.package_name }}"

    # Cargo Packages
    - name: "Install cargo packages"
      when: cargo_packages | length > 0
      become: yes
      community.general.cargo:
        name: "{{ item.package_name }}"
        state: present
      loop: "{{ cargo_packages }}"
      loop_control:
        label: "Installing Cargo package: {{ item.name }} - {{ item.package_name }}"

    # Flatpak Packages
    - name: "Install flatpak packages"
      when: flatpak_packages | length > 0
      become: yes
      community.general.flatpak:
        name: "{{ item.package_name }}"
        state: present
        method: system
      loop: "{{ flatpak_packages }}"
      loop_control:
        label: "Installing Flatpak package: {{ item.name }} - {{ item.package_name }}"

    # Homebrew Packages
    - name: "Install brew packages"
      when: brew_packages | length > 0 and brew_check.rc == 0
      become: yes
      community.general.homebrew:
        name: "{{ item.package_name }}"
        state: present
      loop: "{{ brew_packages }}"
      loop_control:
        label: "Installing Brew package: {{ item.name }} - {{ item.package_name }}"

  # --- Install Error ---
  rescue:
    - name: "Extract failure details safely"
      set_fact:
        failed_package_name: "{{ ansible_failed_result.item.name | default('unknown package') }}"
        failed_package_id: "{{ ansible_failed_result.item.package_name | default('unknown') }}"
        failed_error_msg: "{{ ansible_failed_result.msg | default('Unknown error') }}"

    - name: "Record package failure"
      set_fact:
        failed_installations: "{{ failed_installations + [{
          'name': failed_package_name,
          'package_name': failed_package_id, 
          'msg': failed_error_msg
        }] }}"

    - name: "Log failure to file"
      lineinfile:
        path: "{{ ansible_env.HOME }}/ansible_package_failures.log"
        line: "FAILED | {{ ansible_date_time.iso8601 }} | {{ failed_package_name }} ({{ failed_package_id }}) | {{ failed_error_msg }}"
        create: yes

    - name: "Continue with next package"
      debug:
        msg: "Failed to install {{ failed_package_name }} - continuing..."

# --- Final Summary ---
- name: "Display installation completion"
  debug:
    msg: "Package installation completed!"

- name: "Display failed installations summary"
  when: failed_installations | length > 0
  debug:
    msg: "{{ failed_installations | length }} packages failed to install:"

- name: "Display individual failed packages"
  when: failed_installations | length > 0
  debug:
    msg: "  - {{ item.name }} ({{ item.package_name }}): {{ item.msg }}"
  loop: "{{ failed_installations }}"
