# bootstrap-ansible.yml
- name: "Bootstrap Ansible and dependencies"
  hosts: localhost
  connection: local

  tasks:
    - name: "Install community.general collection"
      ansible.builtin.command: >
        ansible-galaxy collection install community.general
      args:
        creates: "{{ ansible_env.HOME }}/.ansible/collections/ansible_collections/community/general"
