# playbook_dev-tools.yml
- name: "Include Ansible Dependencies"
  import_playbook: playbook_ansible-dependencies.yml

- name: "Common Development Tools"
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    # OS Packages (Common across all distributions)
    os_packages_common:
      # Core Development Tools
      - name: "Git"
        package_name: "git"
        description: "Distributed version control system"
        installer: "os"
      - name: "GNU Make"
        package_name: "make"
        description: "Build automation tool"
        installer: "os"
      - name: "CMake"
        package_name: "cmake"
        description: "Cross-platform build system generator"
        installer: "os"
      - name: "LLVM"
        package_name: "llvm" # Includes GCC and Clang
        description: "Collection of modular and reusable compiler and toolchain technologies"
        installer: "os"
      - name: "pkg-config"
        package_name: "pkg-config"
        description: "Helper tool used when compiling applications and libraries"
        installer: "os"

    # OS Packages (Debian/Ubuntu specific)
    os_packages_debian:
      - name: "VSCodium"
        package_name: "codium"
        description: "Free/Libre Open Source Software Binaries of VSCode"
        installer: "os"

    # OS Packages (Fedora specific)
    os_packages_fedora:
      - name: "VSCodium"
        package_name: "codium"
        description: "Free/Libre Open Source Software Binaries of VSCode"
        installer: "os"

    # OS Packages (Arch specific)
    # os_packages_arch:
    #   - name: "Example Arch Package"
    #     package_name: "example-arch"
    #     description: "An example package for Arch Linux"
    #     installer: "os"

    # AUR Packages (Arch Linux only)
    aur_packages:
      - name: "VSCodium"
        package_name: "vscodium-bin"
        description: "Free/Libre Open Source Software Binaries of VSCode"
        installer: "aur"

    # PIP Packages
    # pip_packages:
    #   - name: "Example PIP Package"
    #     package_name: "example-pip-package"
    #     description: "An example Python package installed via pip"
    #     installer: "pip"

    # Cargo Packages
    # cargo_packages:
    #   - name: "Example Cargo Package"
    #     package_name: "example-cargo-package"
    #     description: "An example Rust package installed via cargo"
    #     installer: "cargo"

    # NPM Packages
    # npm_packages:
    #   - name: "Example NPM Package"
    #     package_name: "example-npm-package"
    #     description: "An example Node.js package installed via npm"
    #     installer: "npm"

    # Flatpak Packages
    # flatpak_packages:
    #   - name: "Example Flatpak Package"
    #     package_name: "org.example.App"
    #     description: "An example Flatpak application"
    #     installer: "flatpak"

  tasks:
    # --- Pre-installation tasks ---
    - name: "Setup VSCodium repositories"
      block:
        - name: "Setup VSCodium repository (Debian)"
          when: ansible_os_family == "Debian"
          block:
            - name: "Add VSCodium GPG key"
              ansible.builtin.get_url:
                url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
                dest: /usr/share/keyrings/vscodium-archive-keyring.gpg
                mode: '0644'
                force: no
              become: yes
    
            - name: "Add VSCodium repository"
              ansible.builtin.copy:
                content: |
                  Types: deb
                  URIs: https://download.vscodium.com/debs
                  Suites: vscodium
                  Components: main
                  Architectures: amd64 arm64
                  Signed-by: /usr/share/keyrings/vscodium-archive-keyring.gpg
                dest: /etc/apt/sources.list.d/vscodium.sources
                mode: '0644'
              become: yes
              notify: update apt cache
    
        - name: "Setup VSCodium repository (Fedora)"
          when: ansible_os_family == "RedHat"
          block:
            - name: "Import VSCodium GPG key"
              ansible.builtin.rpm_key:
                state: present
                key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
              become: yes
    
            - name: "Add VSCodium repository"
              ansible.builtin.copy:
                content: |
                  [gitlab.com_paulcarroty_vscodium_repo]
                  name=download.vscodium.com
                  baseurl=https://download.vscodium.com/rpms/
                  enabled=1
                  gpgcheck=1
                  repo_gpgcheck=1
                  gpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
                  metadata_expire=1h
                dest: /etc/yum.repos.d/vscodium.repo
                mode: '0644'
              become: yes
              notify: update dnf cache

    # --- Install packages using package managers ---
    - name: "Install packages using package managers"
      import_tasks: playbook_package-managers.yml

    # --- Post-installation special tasks ---
