# playbook_ansible-dependencies.yml
- name: "Bootstrap Ansible and dependencies"
  hosts: localhost
  connection: local

  tasks:
    - name: "Install community.general collection"
      command: ansible-galaxy collection install community.general
      register: install_general
      changed_when: '"Nothing to do." not in install_general.stdout'

    - name: "Install kewlfft.aur collection for AUR package management"
      #when: ansible_os_family == "Archlinux"
      command: ansible-galaxy collection install kewlfft.aur
      register: install_aur
      changed_when: '"Nothing to do." not in install_aur.stdout'

    - name: "Create a dedicated user for AUR builds (Arch only)"
      when: ansible_os_family == "Archlinux"
      become: yes
      ansible.builtin.user:
        name: aur_builder
        state: present
        create_home: yes
        shell: /bin/bash

    - name: "Create remote_tmp directory for aur_builder (Arch only)"
      when: ansible_os_family == "Archlinux"
      ansible.builtin.file:
        path: /home/aur_builder/.ansible/tmp
        state: directory
        mode: '0777'
        owner: aur_builder
        group: aur_builder
      become: yes

    - name: "Allow aur_builder to run pacman without a password (Arch only)"
      when: ansible_os_family == "Archlinux"
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        state: present
        validate: "/usr/sbin/visudo -cf %s"
        create: yes
