# playbook.yml
- name: "Bootstrap a new Linux environment (Debian/Fedora/Arch)"
  hosts: localhost
  connection: local

  vars:
    # --- Common Packages (identical names across all distros) ---
    common_packages:
      - git
      - curl
      - fish
      - lsd
      - bat # Installs the binary as 'batcat' in Debian
      - fzf
      - zoxide
      - duf
      - mc
      - entr
      - tealdeer
      - btop
      - micro
      - thefuck
      - figlet
      - cow
      - fortune-mod # Base for fortunes

    # --- Distro-Specific Packages ---
    debian_packages:
      - fonts-firacode # Nerd Font
      - fortune-anarchism
      - anarchism
    fedora_packages:
      - cascadia-code-nf-fonts.noarch # Nerd Font
      - chezmoi # Available in the official repos
    arch_packages:
      - ttf-firacode # Nerd Font
      - chezmoi # Available in the official repos
      - fortune-mod-anarchism # Provides fortune files
      - anarchism

  tasks:
    # --- System-Level Package Installation ---
    - name: "Update package cache and install packages (Debian)"
      become: yes
      ansible.builtin.apt:
        name: "{{ common_packages + debian_packages }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install packages (Fedora/RedHat)"
      become: yes
      ansible.builtin.dnf:
        name: "{{ common_packages + fedora_packages }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: "Install packages (Arch)"
      become: yes
      community.general.pacman:
        name: "{{ common_packages + arch_packages }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Archlinux"

    # --- System-Wide Configuration & Tools ---
    - name: "Link batcat to bat (Debian only)"
      become: yes
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /usr/local/bin/bat
        state: link
      when: ansible_os_family == "Debian"

    - name: "Install Chezmoi via script (for Debian/Fedora)"
      become: yes
      ansible.builtin.shell: 'sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin'
      args:
        creates: /usr/local/bin/chezmoi
      when: ansible_os_family != "Archlinux"

    - name: "Install yay AUR helper (Arch only)"
      block:
        - name: "Install build tools"
          become: yes
          community.general.pacman:
            name: [base-devel, git]
            state: present
        
        - name: "Clone yay repository"
          ansible.builtin.git:
            repo: 'https://aur.archlinux.org/yay.git'
            dest: "/tmp/yay"
        
        - name: "Build and install yay"
          become: no 
          ansible.builtin.shell: "makepkg -si --noconfirm"
          args:
            chdir: "/tmp/yay"
            creates: /usr/bin/yay
      when: ansible_os_family == "Archlinux"

