# playbook_ansible-dependencies.yml
- name: "Bootstrap Ansible and dependencies"
  hosts: localhost
  connection: local

  tasks:
    - name: "Install community.general collection"
      ansible.builtin.command: >
        ansible-galaxy collection install community.general
      args:
        creates: "{{ ansible_env.HOME }}/.ansible/collections/ansible_collections/community/general"

    - name: "Install ansible.posix collection"
      ansible.builtin.command: >
        ansible-galaxy collection install ansible.posix
      args:
        creates: "{{ ansible_env.HOME }}/.ansible/collections/ansible_collections/ansible/posix"

    - name: Install kewlfft.aur collection for AUR package management
      when: ansible_os_family == "Archlinux"
      ansible.builtin.command:
        cmd: ansible-galaxy collection install kewlfft.aur
      args:
        creates: "{{ ansible_env.HOME }}/.ansible/collections/ansible_collections/kewlfft/aur"

    - name: "Create a dedicated user for AUR builds (Arch only)"
      when: ansible_os_family == "Archlinux"
      #become: yes
      ansible.builtin.user:
        name: aur_builder
        state: present
        create_home: yes
        shell: /bin/bash

    - name: "Allow aur_builder to run pacman without a password (Arch only)"
      when: ansible_os_family == "Archlinux"
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        state: present
        validate: "/usr/sbin/visudo -cf %s"
        create: yes
